baseurl = "https://dsbysj.netlify.com/"
languageCode = "en-us"
title = "DS by SJ"
# Define how many pages appear per site
paginate = 10
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command

[params]
    site_author = "Sophia Jensen"
    site_description = "Mercyhurst Intro to Data Science"
    location = "Mercyhurst University"
    # Link custom assets relative to /static
    avatar = "img/Profile.jpg"
    header_background = "img/Header1.jpg"
    header_title = "Data Science by Sophia Jensen"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "lovegracesophia"
    instagram = "lovegracesophia"
    github    = "sjense67"
