---
title: For the Test
author: Sophia Jensen
date: '2017-10-17'
slug: for-the-test
categories:
  - R
tags:
  - data science
  - review
---

Here are some notes from the review session on Monday night:

Make sure that you look for the key words in the questions like sum or average. Take your time and sketch out what information you need, where it's coming from, and how to get it.

Remeber that scatter plots are two sets of data, timeseries are scatterplots with x being time, histograms are one set of data, and bar plots are two sets of data, with one being a factor. Look at the bar plot post on this blog for the line of code to save things as factors. Remember that the column being saved in the one you're going to use as the x axis. 

Always remember to knit! 

Always put a message with your commit, and you only need to init and use the copied lines from github the first time. 

If you have an error come up, try to figure out what it is telling you the problem is, or where it is, before giving up. Look for quotation marks, parentheses, periods, commas, and spaces. Check capitalization. Make sure your libraries are loaded (on your page or dashboard too!). Make sure your consistent in what you're calling different sections of data (remember you have to rename sometimes using AS). 

Most of all, take a deep breath, look at your notes, and know that it's not the end of the world. 

I believe in you all! Best of luck!